In [19]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import time
import json

# Import API key
from config import api_key

# Incorporated citipy to determine city based on latitude and longitude
from citipy import citipy

# Output File (CSV)
output_data_file = "output_data/cities.csv"

# Range of latitudes and longitudes
lat_range = (-90, 90)
lng_range = (-180, 180)

In [20]:
# Output File (CSV)
output_csv = "cities_data.csv"

In [21]:
# Create a dataframe to review information as it comes into the df
latitude = np.random.uniform(low=-90.000, high=90.000, size=50)
longitude = np.random.uniform(low=-180.000, high=180.000, size=50)

cities_df = pd.DataFrame({
    "Latitude": latitude, 
    "Longitude": longitude})

cities_df.head()

    Latitude   Longitude
0   5.325468  141.431560
1 -67.176051  -77.300115
2  83.190036  -42.670914
3  12.647173  -51.943087
4  50.656277   24.516795

## Generate Cities List

In [22]:
# create a params dict that will be updated with new city each iteration
lat = latitude[0]
lon = longitude[0]

params = {
    "key": api_key
}

base_url = "http://api.openweathermap.org/data/2.5/weather?"

query_url = f"http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"

# Get weather data
weather_response = requests.get(query_url)

#Make a list of cities
cities = []

#Loop through the lat/long to add in the find cities
for index, row in cities_df.iterrows():
    
    lat_check = row["Latitude"]
    lng_check = row["Longitude"]
    
    cityNow = citipy.nearest_city(lat_check, lng_check).city_name
    country = citipy.nearest_city(lat_check, lng_check).country_code
    print(cityNow)
    print(country)
    

    cities_df.set_value(index, "Latitude" , lat_check)
    cities_df.set_value(index, "Longitude", lng_check)
    cities_df.set_value(index, "City"     , cityNow)
    cities_df.set_value(index, "Country"     , country)
        
    # If the city is unique, then add it to a our cities list
    if cityNow not in cities:
        cities.append(cityNow)

airai
pw
ushuaia
ar
ilulissat
gl
mana
gf
lokachi
ua
along
in
ushuaia
ar
rikitea
pf
changli
cn
bluff
nz
vila franca do campo
pt
mar del plata
ar
viligili
mv
marsa matruh
eg
jaru
br
lompoc
us
shenjiamen
cn
shingu
jp
sept-iles
ca
airai
pw
sentyabrskiy
ru
constitucion
mx
labuan
my
orapa
bw
dikson
ru
bolshaya vishera
ru
marquette
us
jamestown
sh
ilulissat
gl
ust-kamchatsk
ru
rikitea
pf
castro
cl
dikson
ru
mayo
ca
hobart
au
karpathos
gr
rikitea
pf
hilo
us
rikitea
pf
chokurdakh
ru
hermanus
za
ilulissat
gl
cape town
za
tofield
ca
rikitea
pf
padang
id
port alfred
za
esperance
au
monrovia
lr
yellowknife
ca

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:31: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:32: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:33: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:34: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead

In [23]:
cities_df.head()

    Latitude   Longitude       City Country
0   5.325468  141.431560      airai      pw
1 -67.176051  -77.300115    ushuaia      ar
2  83.190036  -42.670914  ilulissat      gl
3  12.647173  -51.943087       mana      gf
4  50.656277   24.516795    lokachi      ua

## Perform API Calls

In [24]:
# OpenWeatherMap API Key
#api_key = api_key.api_key

#units = "imperial"

# Starting URL for Weather Map API Call
#url = "http://api.openweathermap.org/data/2.5/weather?units=Imperial&APPID=" + api_key 
#url = "http://history.openweathermap.org/data/2.5/history/accumulated_temperature?lat={lat}&lon={lon}&start=1420070400&end=1514764800&threshold=54000"
lat = latitude[0]
lon = longitude[0]

# Starting URL for Weather Map API Call
#url= "http://api.openweathermap.org/data/2.5/weather?id=2172797&appid=" + api_key 
query_url = f"http://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={api_key}"

#print(url)
print(requests.get(query_url))

<Response [200]>

In [25]:
# Get weather data
weather_response = requests.get(query_url)
weather_json = weather_response.json()

print(json.dumps(weather_json, indent=4, sort_keys=True))

{
    "base": "stations",
    "clouds": {
        "all": 32
    },
    "cod": 200,
    "coord": {
        "lat": 5.33,
        "lon": 141.43
    },
    "dt": 1532368604,
    "id": 0,
    "main": {
        "grnd_level": 1022.47,
        "humidity": 100,
        "pressure": 1022.47,
        "sea_level": 1022.52,
        "temp": 300.211,
        "temp_max": 300.211,
        "temp_min": 300.211
    },
    "name": "",
    "sys": {
        "message": 0.0039,
        "sunrise": 1532291366,
        "sunset": 1532335926
    },
    "weather": [
        {
            "description": "scattered clouds",
            "icon": "03n",
            "id": 802,
            "main": "Clouds"
        }
    ],
    "wind": {
        "deg": 187.509,
        "speed": 5.47
    }
}

In [36]:
# Add additional columns needed for analysis
#cities_df["City"] = ""
cities_df["High Temp."] = ""
cities_df["Humidity"] = ""
#cities_df["Cloud Cover"] = ""
cities_df["Wind Speed"] = ""

In [37]:
Lats = cities_df["Latitude"].tolist()
Lngs = cities_df["Longitude"].tolist()

In [39]:
windspeed = []

for i in range(len(Lats)):
    latNow = Lats[i]
    lngNow = Lngs[i]
    
    query_url = f"http://api.openweathermap.org/data/2.5/weather?lat={latNow}&lon={lngNow}&appid={api_key}"

    weatherNow = requests.get(query_url).json()
    windspeed = weatherNow["wind"]["speed"]
    
    cities_df.set_value(i, "Wind Speed", windspeed)
    
    
    wind_value = {
        "cityID":i,
        "windspeed":windspeed, 
        "lat":latNow,
        "lng":lngNow
    }
    windspeed.append(wind_value)
    
    

cities_df.head()

#pd.DataFrame(ListV)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:12: FutureWarning: set_value is deprecated and will be removed in a future release. Please use .at[] or .iat[] accessors instead
  if sys.path[0] == '':

AttributeError: 'float' object has no attribute 'append'

In [35]:
for index, row in cities_df.iterrows():
    # get lat, lng from df
    lat = row["Latitude"]
    lng = row["Longitude"]

    # change location each iteration while leaving original params in place
    params["location"] = f"{lat},{lng}"

    # Use the search term: "International Airport" and our lat/lng
    base_url = "http://api.openweathermap.org/data/2.5/weather?"


    # make request and print url
    city_weather = requests.get(base_url, params=params)
    
#     print the name_address url, avoid doing for public github repos in order to avoid exposing key
#     print(name_address.url)

    # convert to json
    city_weather = city_weather.json()
    # print(json.dumps(name_address, indent=4, sort_keys=True))

    # Since some data may be missing we incorporate a try-except to skip any that are missing a data point.
    try:
        cities_df.loc[index, "High Temp."] = city_weather["main"][0]["temp_max"]
        cities_df.loc[index, "Humidity"] = city_weather["main"][0]["humidity"]
        cities_df.loc[index, "Wind Speed"] = city_weather["wind"][0]["speed"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.
Missing field/result... skipping.

In [31]:
cities_df.head()

    Latitude   Longitude       City Country High Temp. Humidity Wind Speed
0   5.325468  141.431560      airai      pw
1 -67.176051  -77.300115    ushuaia      ar
2  83.190036  -42.670914  ilulissat      gl
3  12.647173  -51.943087       mana      gf
4  50.656277   24.516795    lokachi      ua